### ISSUE TITLE
Possibility to toggle the lichess chess.com logo on and off

### ISSUE THREAD

**Issue by lbruneteau** [ducksper/lichess_enhancement#1]
With this extension (I'm using firefox but it certainly doesn't matter) I have a chess.com lichess logo in the top left corner of the screen. However I like the default lichess logo much better. I think there should be a way to keep the old lichess logo. What I think would be the best would be a way to chose your logo in the extension's settings. Is there any way we could have this please ?

**Comment by ducksper** [comment]
Sorry for the late reply
I will update to put back the original logo

**Comment by lbruneteau** [comment]
Thanks

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Duck ***@***.***>
Envoyé : Monday, April 26, 2021 2:18:35 PM
À : ducksper/lichess_enhancement ***@***.***>
Cc : Louis BRUNETEAU ***@***.***>; Author ***@***.***>
Objet : Re: [ducksper/lichess_enhancement] Possibility to toggle the lichess chess.com logo on and off (#1)


Sorry for the late reply
I will update to put back the original logo

**Comment by ducksper** [comment]
done lol #bb4410f37d763def5b4449e5408f4be1341f6edb
