### ISSUE TITLE
Board change stopped working

### ISSUE THREAD

**Issue by FedericoBarberon** [ducksper/lichess_enhancement#10]
With the new lichess update the board change doesnt work anymore
![image](https://github.com/ducksper/lichess_enhancement/assets/66987826/5bc3d776-0e17-4ca2-92c3-e0fc52f2857b)

**Comment by chk-L** [comment]
I'm having this same issue. The pieces changes, but the board not. Is there a way to fix it?

**Comment by Sasivama** [comment]
Same issue here as well
